pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - python setup.py install
      - pip install -r dev-requirements.txt
      - pytest
  doc:
    image: python:${PYTHON_VERSION}
    commands:
      - python setup.py install
      - pip install -r dev-requirements.txt
      - make doc
      - rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/aiohttp_helpers
      - mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/aiohttp_helpers
      - cp -Rf doc/_build/html/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/aiohttp_helpers/
    when:
      event: push
      branch: [ master, pci_* ]
    volumes:
      - /pub:/pub

matrix:
  PYTHON_VERSION:
    - 3.5-jessie

branches: [ master, pci_*, ci_* ]
